#!/bin/bash

pass='number1 number2 number 3 number4 number12 number13 number14 number15 number16'
chk='number15'
result="Not Found!"

echo -n "Working... "
echo -ne "\033[1;32m\033[7m\033[?25l"

for i in $(seq 1 60); do
   sleep 0.1
   if [ $i -eq 60 ]; then
      result="Done"
      break
   else
      echo -n " "
   fi
done

printf " \033[0m "
printf "\nDone!\n"