#!/bin/bash

phases=( 
    'Doing stuff...'
    'Thinking...'
    'Doing more stuff...'
    'Doing a little more extra stuff...'
    'Almost there...'
)   

for i in $(seq 1 100); do  
    sleep 0.1
    if [ $i -eq 100 ]; then
        echo -e "XXX\n100\nDone!\nXXX"
    elif [ $(($i % 20)) -eq 0 ]; then
        let "phase = $i / 20"
        echo -e "XXX\n$i\n${phases[phase]}\nXXX"
    else
        echo $i
    fi 
done | whiptail --title 'Example progress bar' --gauge "${phases[0]}" 6 60 0